on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

name: Mirror GitHub Selected Repos to Gitee
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Mirror Github to Gitee with white list
      uses: Yikun/hub-mirror-action@master
      with:
        src: aliyun/xionglilonggithub/tianxinying-xy
        dst: aliyun/xionglilong
        dst_key: ${{ secrets.ALIYUN_PRIVATE_KEY }}
        dst_token:  ${{ secrets.ALIYUN_TOKEN }}
        static_list: 'Synchronous-library.github.io'
        force_update: true